### ISSUE TITLE
bbox_annos_() 方法定义位置

### ISSUE THREAD

**Issue by zaofengzhou** [menjingru/vnet#1]
代码好像跑步起来？bbox_annos_() 方法定义在find_mhd_path()之前似乎会报该方法找不到的错。

**Comment by menjingru** [comment]
你试着调整下位置，我更新了代码还没上传，晚上传



---原始邮件---
发件人: "ZaoFeng ***@***.***&gt;
发送时间: 2021年12月4日(周六) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [menjingru/vnet] bbox_annos_() 方法定义位置 (Issue #1)




 
代码好像跑步起来？bbox_annos_() 方法定义在find_mhd_path()之前似乎会报该方法找不到的错。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zaofengzhou** [comment]
resolved

**Comment by menjingru** [comment]
It is because there is an extra "()" at the end of line 11 of mask_xml.py, which has been corrected on github


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "menjingru/vnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 晚上7:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [menjingru/vnet] bbox_annos_() 方法定义位置 (Issue #1)





 
resolved
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
